[phases.setup]
nixPkgs = [
  "php81",
  "php81Extensions.pdo_mysql",
  "php81Extensions.fileinfo",
  "composer",
  "nodejs-18_x",
  "npm"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan storage:link",
  "npm run build"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
