[phases.setup]
nixPkgs = [
  "php81",
  "php81Extensions.pdo_mysql",
  "php81Extensions.fileinfo",
  "nodejs-18_x",
  "npm",
  "curl"  # untuk install composer manual
]

[phases.install]
cmds = [
  # install composer secara manual
  "curl -sS https://getcomposer.org/installer | php",
  "mv composer.phar /usr/local/bin/composer",
  
  # install Laravel dependencies
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan storage:link",
  "npm run build"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
